---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: metrics-app
  namespace: acm-poc-devteam1
spec:
  selector:
    matchExpressions:
      - key: application
        operator: In
        values:
        - metrics-app
